feat(project): improve logs and clipboard management

diff --git a/.local/sd/project/create b/.local/sd/project/create
--- a/.local/sd/project/create
+++ b/.local/sd/project/create
@@ -5,10 +5,22 @@
 # This will create project folders in the $PROJECTS_ARCHIVE and link it in the $PROJECTS_PATH
 # To remove it use the sd project unlink
 
-set -euo pipefail
+source ${HOME}/.local/lib/log
 
 projects_archive=${PROJECTS_ARCHIVE:-${HOME}/work/subjects}
 projects_path=${PROJECTS_PATH:-${HOME}/projects/}
 
+
 mkdir -p ${projects_archive}/${1} ${projects_path}
-ln -sf -t ${projects_path} ${projects_archive}/${1}
+
+if [ -z $1 ]; then
+  log_error "project" "no project name was specified"
+  exit 1
+fi
+
+if ln -sf -t ${projects_path} ${projects_archive}/${1}; then
+  log_info "project" "successfully created project $1"
+else
+  log_error "project" "couldn't create project $1"
+  exit 1
+fi
